### ISSUE TITLE
appDirectory broken

### ISSUE THREAD

**Issue by xHomu** [kiliman/remix-express-vite-plugin#11]
Using `appDirectory` option in remix config creates invalid network request:

![image](https://github.com/kiliman/remix-express-vite-plugin/assets/84349818/a462f1d7-1f00-449e-95ea-9b7cc660947b)

Reproduction: https://github.com/xHomu/rev-appDirectory-bug

Based on the example app, commit https://github.com/xHomu/rev-appDirectory-bug/commit/7e53539dcd37a1d31334fdef243edf148efa8a97 adds `appDirectory: "remix-app"` and moves `/app` to `/remix-app`, which triggers the errors and breaks hmr.

Windows environment if that makes a difference here.

**Comment by xHomu** [comment]
Don't happen when `expressDevServer()`  was commented out, so I believe this is a REV issue.

**Comment by kiliman** [comment]
Yeah, if you look at these lines, it ignores requests that start with `/app`

https://github.com/kiliman/remix-express-vite-plugin/blob/7979c1e770660312f9197c10413aea41d18fd738/packages/remix-express-dev-server/src/index.ts#L32-L33

There's a lot of internal requests that Vite makes to support HMR. I haven't verified what it should look like for routes that start with `/app`.

I should be able to fix this.

**Comment by kiliman** [comment]
Fixed in v0.2.1

**Comment by xHomu** [comment]
Can confirm the fix! https://github.com/xHomu/rev-appDirectory-bug/commit/e733fa6af15f4435fa85e8d36f496313a7ce7e78
