### ISSUE TITLE
Routes starting with "/app" are ignored when setting-up middlewares in Dev mode.

### ISSUE THREAD

**Issue by PhilDL** [kiliman/remix-express-vite-plugin#12]
Hello, there seems to be an edge case in **dev mode only** if we are using routes paths starting with "/app". 

Here is a reproduction based on the example you shared earlier, default vite config (no `appDirectory` set):

https://stackblitz.com/edit/github-spaqp1-rigwyn?file=app%2Froutes%2F_protected.app.tsx
- `routes`
    - `_protected.app.tsx` This is working
    - `_protected.app.no-context.tsx` This route don't have access to middleware context.

The problem seems to be [`packages/remix-express-dev-server/src/index.ts`](https://github.com/kiliman/remix-express-vite-plugin/blob/05f715e371bb0a1aa1668874a59ccdca9f3034a1/packages/remix-express-dev-server/src/index.ts#L26C59-L26C71) that construct an exclude pattern for the app **folder**, indadvertedly also excluding routes starting with app.

**Comment by kiliman** [comment]
Interesting. I'll take a look. But the regex explicitly checks for requests that start with `/<appdir>/`. See the `^` in the regex `new RegExp(`^${escapeRegExp(appDirectory)}`)

Vite requests the actual path, like `/app/routes/_protected.app.no-context`, and we only want to send those requests to the Vite dev server, not Express.

I'm not sure if the ignore pattern is picking this up or if it's an issue with the middleware handling. Thanks for the repro. I'll dig into this.

**Comment by kiliman** [comment]
Ok, I found the issue. It'll be fixed in the next update.

**Comment by kiliman** [comment]
Fixed in `remix-express-dev-server` v0.2.4
