### ISSUE TITLE
Run Next and Remix on the same server

### ISSUE THREAD

**Issue by xHomu** [kiliman/remix-express-vite-plugin#13]
I'm trying to migrate an existing express app that have some additional nextjs routes, based on [sergio's article](https://sergiodxa.com/tutorials/run-next-and-remix-on-the-same-server).

It works as a stand-alone express.ts server, but I couldn't quite get it working with this plugin, am I incorrect to insert the next paths in configure?

Reproduction: https://github.com/xHomu/remix-express-vite-plugin/tree/add-next-routes/example/remix-vite-express

navigating to `localhost:3000/my-route` returns a Remix route-not-found error:
![image](https://github.com/kiliman/remix-express-vite-plugin/assets/84349818/9c1083ea-a911-457d-bd38-82d348f334bd)

```jsx
// This creates an express server that runs inside vite
export const app = createExpressApp({
  configure: async app => {
    // customize your express app with additional middleware
    app.use(compression())
    app.disable('x-powered-by')
    app.use(morgan('tiny'))

    // Initiate Next Handler
    const nextApp = next({ dev: true })
    const handle = nextApp.getRequestHandler()
    await nextApp.prepare()

    console.log('Next.js is ready')

    // @ts-expect-error test yadayada
    function nextHandler(req, res) {
      return handle(req, res)
    }

    app.all('/my-route', nextHandler)
    app.all('/_next/*', nextHandler)
  },
```

https://github.com/xHomu/remix-express-vite-plugin/blob/add-next-routes/example/remix-vite-express/remix-app/app.server.ts#L16

Just in case, I tested the route on a vanilla express server via `npm run dev-next: node server.js` and `localhost:3000/my-route` worked.

**Comment by kiliman** [comment]
Hmm... it should work. I'll see if I can figure it out. Everything from configure is added to the express app first, followed by static and remix build assets, then finally the remix request handler.

As long as your middleware handler doesn't call next, it should not fall through to remix.

**Comment by kiliman** [comment]
This works, so looks like something with the real next handler. I'll keep checking.

```ts
export const app = createExpressApp({
  configure: app => {
    // customize your express app with additional middleware
    app.use(morgan('tiny'))

    function nextHandler(req: any, res: any) {
      res.send('hello from next: ' + req.url)
    }

    app.all('/my-route', nextHandler)
    app.all('/_next/*', nextHandler)
  },
})
```

<img width="371" alt="image" src="https://github.com/kiliman/remix-express-vite-plugin/assets/47168/ee9e944d-7f2a-4075-b6b4-6db3a46a9dc8">
<img width="389" alt="image" src="https://github.com/kiliman/remix-express-vite-plugin/assets/47168/96483d82-b23a-46ea-a83b-30280d949333">


<img width="376" alt="image" src="https://github.com/kiliman/remix-express-vite-plugin/assets/47168/2d61da7d-fdd3-422d-bcb8-01236c1f36fa">

**Comment by kiliman** [comment]
OK, I commented out where I set up the remix handler, and the next app ran just fine inside my vite plugin. I just need to figure out why it's falling through after the next handler executes.

<img width="752" alt="image" src="https://github.com/kiliman/remix-express-vite-plugin/assets/47168/6ae2fea5-cee7-4235-b391-45ffdd009b2c">

<img width="636" alt="image" src="https://github.com/kiliman/remix-express-vite-plugin/assets/47168/b2fc09eb-45a0-460d-b280-16a9aded6a1d">

**Comment by kiliman** [comment]
Ok, I figured out the issue. You made your configure function async, which was not expected.

I moved the next app initialization outside of configure, and it works now.

Let me think if I want to support async configure. But this should work now.

```ts
import morgan from 'morgan'
import { createExpressApp } from 'remix-create-express-app'
import { sayHello } from './hello.server'
import { AppLoadContext } from '@remix-run/node'
import compression from 'compression'
import next from 'next'

console.log('initializing Next.js')
const nextApp = next({ dev: true })
const handle = nextApp.getRequestHandler()
await nextApp.prepare()
console.log('Next.js is ready')

// This creates an express server that runs inside vite
export const app = createExpressApp({
  configure: app => {
    // customize your express app with additional middleware
    app.use(compression())
    app.disable('x-powered-by')
    app.use(morgan('tiny'))

    // @ts-expect-error test yadayada
    function nextHandler(req, res) {
      console.log('handling next route', req.url)
      return handle(req, res)
    }

    console.log('setting up next routes')
    app.all('/my-route', nextHandler)
    app.all('/_next/*', nextHandler)
  },
  getLoadContext: () => {
    // return the AppLoadContext
    return { sayHello } as AppLoadContext
  },
  unstable_middleware: true,
})
```
<img width="774" alt="image" src="https://github.com/kiliman/remix-express-vite-plugin/assets/47168/3b7897f9-9182-4af0-aa50-2ef0521ad74f">

**Comment by kiliman** [comment]
Note, if you have any links in your Remix app to your Next app, make sure you either use regular `<a href>` tags or `<Link to reloadDocument>` to ensure that React Router doesn't try to process the link.
```ts
<ul>
  <li>
    <Link to="/test">Test</Link>
  </li>
  <li>
    <Link to="/my-route" reloadDocument>
      Next.js /my-route
    </Link>
  </li>
</ul>
```

**Comment by xHomu** [comment]
Ah, async functions reared their ugly head again! I was worried about the next.initiate function not running.

**Comment by kiliman** [comment]
Is it working for you now with the next app setup outside your configure function?

**Comment by xHomu** [comment]
Can confirm that moving the async functions out fixed the issue! 
![image](https://github.com/kiliman/remix-express-vite-plugin/assets/84349818/046cb48e-3732-4abe-ae89-68cc201fcb45)
