### ISSUE TITLE
Middleware not applied on ambiguous POST index route with `xxxx.data?index`

### ISSUE THREAD

**Issue by PhilDL** [kiliman/remix-express-vite-plugin#14]
Hello, and sorry to bother you again 😅.

When letting Remix handle a form `action` (leaving it empty) from an ambiguous index route (could have a layout route at the same level), it will add `?index` to the url to POST to, for example:

`POST /dashboard.data?index 500 - - 35.760 ms` 

In these case the middlewares are not applied because the url doesn't ends with `.data` but `.data?index`.

Here is a reproduction based on the example you shared some time ago, where I modified the route structure to 
make `/dashboard` route ambiguous:

https://stackblitz.com/edit/github-spaqp1-en4yxf?file=app%2Froutes%2F_protected.dashboard._index.tsx

Problematic line may be [packages/remix-create-express-app/src/middleware.ts](https://github.com/kiliman/remix-express-vite-plugin/blob/72af9f7b4e36982476c86401982bef95a658abdc/packages/remix-create-express-app/src/middleware.ts#L56)

**Comment by kiliman** [comment]
Thanks for these bug reports. Yes, I definitely should check for a query string.

I'll get this fixed.

**Comment by kiliman** [comment]
This is fixed in v0.3.7

**Comment by kiliman** [comment]
Updated StackBlitz

https://stackblitz.com/edit/github-spaqp1-7wkbae?file=app%2Froutes%2F_protected.dashboard._index.tsx
