### ISSUE TITLE
createExpressApp called twice in development

### ISSUE THREAD

**Issue by thomaswelton** [kiliman/remix-express-vite-plugin#24]
When running in dev mode I can see that the `entry.server` file is loaded twice. As a result `createExpressApp` is called twice.
This is an issue as if I add express middleware like prometheus metrics they will be registered twice which will throw an error. 

Replication steps
- Add some logging above the `createExpressApp` function call. Or inside of the `configure` option in the `entry.server`
- See that this is logged twice after restarting the server

**Comment by thomaswelton** [comment]
@kiliman Thanks for the commit and fix here. See https://github.com/kiliman/remix-express-vite-plugin/pull/25 for an alternative approach and discussion.


Screenshot below is using your new code.
This change has prevented configure from being called twice during local dev. However the entry file is still being loaded or called twice.

![image](https://github.com/kiliman/remix-express-vite-plugin/assets/678372/e842d0c3-5eb6-4453-83be-eae2eb16805d)


This will be an issue as we will want to do some async setup before the call to `createExpressApp` 
Something like
```js
const expressApp = express();

await setupGraphServerAndPrommetrics(expressApp);

export const app = createExpressApp({
  getExpress: () => expressApp,
  unstable_middleware: true,
  buildDirectory: 'remix-build',
  serverBuildFile: 'index.mjs'
});
```

Where `setupGraphServerAndPrommetrics` would throw an error if it's called twice.

**Comment by thomaswelton** [comment]
Looking at it, I'd still run into issues during any HMR of the express server as the entry point would be run again anyway.
So I'll need to address that either way.

**Comment by kiliman** [comment]
Does v0.2.7 fix your issue?

**Comment by BearKid** [comment]
> Does v0.2.7 fix your issue?

Hi @kiliman , it seems the issue is not fixed.
Hi @thomaswelton , do you solve the problem with another approach?

I'm currently experiencing the same problem as @thomaswelton , except that my scenario is to setup scheduled tasks.

I am using:
* remix-express-dev-server@0.4.4
* remix-create-express-app@0.4.5

**Comment by thomaswelton** [comment]
I am no longer using this plugin. I was just using this as an easy way to get the whole application bundled with vite. I not use the examples set out here https://github.com/remix-run/react-router-templates/blob/main/node-custom-server/server.js
