### ISSUE TITLE
remix-express-dev-server 0.2.7 awaited code error

### ISSUE THREAD

**Issue by xHomu** [kiliman/remix-express-vite-plugin#26]
remix-express-dev-server 0.2.7 introduced a change to when awaited server code runs, triggering errors when accessing server context:

Repro: https://github.com/manawiki/api-standalone-simple

1. copy .env.example to .env, update MONGODB_URL with a working Mongodb connection string
2. npm install; npm run dev

Error:

![image](https://github.com/kiliman/remix-express-vite-plugin/assets/84349818/9395f44f-484b-4d3a-8932-e22b7b25732d)

Expected:

![image](https://github.com/kiliman/remix-express-vite-plugin/assets/84349818/aa1e9469-390c-4388-8533-6d3524a5d68a)

`payload.find` is initialized before passing into server context here: https://github.com/manawiki/api-standalone-simple/blob/main/app/app.server.ts#L25

* Downgrade to remix-express-dev-server 0.2.6 fixes the error
* The error also goes away after the initial load

**Comment by kiliman** [comment]
Can you test your app with the latest v0.4.0 (both packages).

Thanks!

**Comment by xHomu** [comment]
Looks like it's working, thanks!
